# docker-compose.yml
version: '3.5'

services:
  monolith:
    image: poncheska/monolith:latest
    ports:
      - 8080:8080
    environment:
      - HANDLER_GRT=10
      - HANDLER_TOL=4
      - CFG_VAL=kek