apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-ms-deployment-autoscaling
  labels:
    app: k8s-analysis
spec:
  selector:
    matchLabels:
      project: fast-ms
  template:
    metadata:
      labels:
        project: fast-ms
    spec:
      containers:
        - name: fast-ms-cntr
          image: poncheska/fast-ms:latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: CFG_VAL
              value: kek
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fast-ms-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: fast-ms-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fast-ms-service
  labels:
    app: k8s-analysis
spec:
  type: NodePort
  selector:
    project: fast-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-ms-deployment-autoscaling
  labels:
    app: k8s-analysis
spec:
  selector:
    matchLabels:
      project: slow-ms
  template:
    metadata:
      labels:
        project: slow-ms
    spec:
      containers:
        - name: slow-ms-cntr
          image: poncheska/slow-ms:latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: CFG_VAL
              value: kek
            - name: HANDLER_GRT
              value: 10
            - name: HANDLER_TOL
              value: 4
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: slow-ms-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: slow-ms-deployment-autoscaling
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: slow-ms-service
  labels:
    app: k8s-analysis
spec:
  type: NodePort
  selector:
    project: slow-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ms
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ingress-ms-ip
  labels:
    app: k8s-analysis
spec:
  rules:
    - http:
        paths:
          - path: "/slow"
            backend:
              serviceName: slow-ms-service
              servicePort: 80

          - path: "/fast"
            backend:
              serviceName: fast-ms-service
              servicePort: 8080