apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-ms-deployment-autoscaling
  labels:
    app: k8s-analysis
spec:
  selector:
    matchLabels:
      project: fast-ms
  template:
    metadata:
      labels:
        project: fast-ms
    spec:
      containers:
        - name: fast-ms-cntr
          image: poncheska/fast-ms:latest
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fast-ms-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: fast-ms-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fast-ms-service
  labels:
    app: k8s-analysis
spec:
  selector:
    project: fast-ms
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-ms-deployment-autoscaling
  labels:
    app: k8s-analysis
spec:
  selector:
    matchLabels:
      project: slow-ms
  template:
    metadata:
      labels:
        project: slow-ms
    spec:
      containers:
        - name: slow-ms-cntr
          image: poncheska/slow-ms:latest
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: slow-ms-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: slow-ms-deployment-autoscaling
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: slow-ms-service
  labels:
    app: k8s-analysis
spec:
  selector:
    project: slow-ms
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ms
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ingress-ms-ip
  labels:
    app: k8s-analysis
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/slow"
            backend:
              service:
                name: slow-ms-service
                port:
                  number: 8080

          - pathType: Prefix
            path: "/fast"
            backend:
              service:
                name: fast-ms-service
                port:
                  number: 8080